In [1]:
import numpy as np
import test_module

a = np.ones((2,3), dtype=np.int32)
print(a)
test_module.test(a)
print(a)

[[1 1 1]
 [1 1 1]]

Hello from C++

Array shape: 2 x 3 

[[42 42 42]
 [42 42 42]]


In [2]:
a = np.ones((5,5), dtype=np.int32)
print(a)
test_module.random_test(a)
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

Hello from random C++

Generating random values for array shape: 5 x 5 

[[3 3 5 4 0]
 [5 4 0 5 5]
 [1 0 5 1 0]
 [5 3 4 2 5]
 [5 3 1 4 2]]


In [3]:
import numpy as np
import spins_module

a = np.ones((2,3), dtype=np.int32)
print(a)
spins_module.test(a)
print(a)

[[1 1 1]
 [1 1 1]]

Hello from C++

Array shape: 2 x 3 

[[50 50 50]
 [50 50 50]]
